### ISSUE TITLE
Request to fill in "requirements.txt"

### ISSUE THREAD

**Issue by dmalawey** [ansarid/scuttlepy#5]
Is this file intended to list the required libraries for running this code?

Can we get a first-draft of this list of requirements please?

**Comment by ansarid** [comment]
@dmalawey that's actually a job for `setup.py`. I have added all the latest dependencies to `setup.py`.
The purpose of `requirements.txt` is for setting up your development environment if you want to modify the SCUTTLEPy software without running `setup.py`. But if you are developing the  SCUTTLEPy software, it's still likely you're installing it to test it using `setup.py`.

Long story short, please run `sudo python3 setup.py install` to install the SCUTTLEPy library and all its required components.
